version: '3'
services:
  redis-server:
      image: "redis:alpine"
      ports:
          - "6379:6379" 
  prometheus:
      image: prom/prometheus:v2.21.0
      network_mode: "host"
      volumes:
        - ./prometheus:/etc/prometheus
        - prometheus-data:/prometheus
volumes:
  prometheus-data:
