global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: 'backend'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'localhost:7000'