const SEARCH_FOR_BLOGS_AND_WRITERS = 'SEARCH_FOR_BLOGS_AND_WRITERS'
const SEARCH_FOR_BLOGS = 'SEARCH_FOR_BLOGS'
const SEARCH_FOR_WRITERS = 'SEARCH_FOR_WRITERS'
const SEARCH_FOR_TAGS = 'SEARCH_FOR_TAGS'

export {SEARCH_FOR_BLOGS, SEARCH_FOR_WRITERS, SEARCH_FOR_BLOGS_AND_WRITERS, SEARCH_FOR_TAGS}