const SEARCH_FOR_ALL = 'SEARCH_FOR_ALL'
const SEARCH_FOR_BLOGS = 'SEARCH_FOR_BLOGS'
const SEARCH_FOR_WRITERS = 'SEARCH_FOR_WRITERS'
const SEARCH_FOR_TAGS = 'SEARCH_FOR_TAGS'
const SEARCH_FOR_BLOG_BY_TAG = 'SEARCH_FOR_BLOG_BY_TAG'

export {SEARCH_FOR_BLOG_BY_TAG, SEARCH_FOR_BLOGS, SEARCH_FOR_WRITERS, SEARCH_FOR_ALL, SEARCH_FOR_TAGS}